### PR TITLE
Fix parsing of tags containing "00".

### LINKED ISSUE #18: githttp.RpcReader: Fails to correctly detect tags with "00" in name; multiple tags.
Consider a situation where you create a tag that contains "00" in its name.

`githttp.RpcReader` currently fails to correct detect its name. It happens because the "00" part of the tag name matches the "00" at the end of the current regexp:

```Go
"([0-9a-fA-F]{40}) ([0-9a-fA-F]{40}) refs\\/(heads|tags)\\/(.*?)( |00|\x00)"
```

It may also fail to detect when multiple tags are pushed at the same (if they contain "00"), e.g.:

```
git tag 1.000.1
git tag 1.000.2
git tag 1.000.3
git push --tags
```

That pushes 3 tags, but they won't all be detected correctly.

### PR DESCRIPTION
**Pull request by shurcooL**
Previous regexp would falsely match tag names that contained "00" as the end of line/separator marker, thus incorrectly reporting tag names (they'd be cut off just before the first "00").

Change pktLineParser output to be a slice of lines rather than the combined total. This preserves original line separation information, and it's still possible to get the total when desired by concatenating all lines.

Fix the tag name with "00" issue by inspecting each pkt-line individually, which will contain at most one tag name. Simplify the regexp to avoid false matches. Add a TODO comment to move towards completely eliminating the use of regexes since it's not an appropriate tool for this task. /cc @slimsag

Add tests. /cc @keegancsmith

Fixes #18.

### CODE REVIEW

**Comment by shurcooL** [comment]
Any review comments here?

**Comment by shurcooL** [comment]
Friendly ping. /cc @AaronO

**Comment by shurcooL** [comment]
@AaronO, have you had a chance to look at this yet?

You should see the issue that this resolves described in #18.

This PR adds tests that pass, but if you tried those tests with the current `master` version, they will fail.

We've been using the version in this PR at Sourcegraph with no issues so far.

**Comment by AaronO** [comment]
@shurcooL Sorry, been very busy lately. I'm adding travis builds to `go-git-http`, then I'll merge.

**Comment by AaronO** [comment]
Merged! Thanks for the great PR once again :+1:

**Comment by shurcooL** [comment]
Thanks for merging!

**Pull request merged**
