### PR TITLE
Significantly refactor and improve RpcReader.

### LINKED ISSUE #13: githttp.RpcReader: Incorrect io.Reader output usage.
Hi, thanks for this useful library!

I'd like to report an issue I discovered in the code of `githttp.RpcReader`.

In the following code:

```Go
// Implement the io.Reader interface
func (r *RpcReader) Read(p []byte) (n int, err error) {
	// Relay call
	n, err = r.Reader.Read(p)

	// Scan for events
	if err == nil || err == io.EOF {
		r.scan(p)
	}

	return n, err
}
```

There's a problem with the `if err == nil || err == io.EOF { r.scan(p) }` statement.

According to docs of [`io.Reader`](https://godoc.org/io#Reader):

> Read reads up to len(p) bytes into p. It returns the number of bytes read (0 <= n <= len(p)) and any error encountered.

> Callers should always process the n > 0 bytes returned before considering the error err. Doing so correctly handles I/O errors that happen after reading some bytes and also both of the allowed EOF behaviors.

`Read` is not guaranteed to read exactly `len(p)` bytes, it may read less than that and still return a nil error. If that happens, calling `r.scan(p)` will provide invalid data, since not all of `p` has been read into.

The correct way to process the output of `Read`, as suggested by the documentation, is like this:

```Go
// Scan for events
if n > 0 {
	r.scan(p[:n])
}
```

The `n > 0` check is optional, but it makes it so that empty byte slice is not sent to `scan`, since that's not helpful. Omitting it would also be correct.

I have a PR coming that will resolve this issue.

### LINKED ISSUE #14: githttp.RpcReader: Regexp matching may have false negatives depending how multiple Read boundaries are aligned.
Consider this code:

```Go
// Implement the io.Reader interface
func (r *RpcReader) Read(p []byte) (n int, err error) {
	// Relay call
	n, err = r.Reader.Read(p)

	// Scan for events
	if err == nil || err == io.EOF {
		r.scan(p)
	}

	return n, err
}
```

`r.scan(p)` is called with a segment of read data that is in `p`, and that is then immediately matched against a regexp.

Imagine the regexp is trying to match the following string:

```
0000000000000000000000000000000000000000 92eef6dcb9cc198bc3ac6010c108fa482773f116 refs/heads/master 
```

Due to chance, the first value of `p` may be:

```
0000000000000000000000000000000000000000 92
```

During the next read, the value of `p` may be:

```
eef6dcb9cc198bc3ac6010c108fa482773f116 refs/heads/master
```

Since the regexp tries to match the entire line at a time:

```Go
var receivePackRegex = regexp.MustCompile("([0-9a-fA-F]{40}) ([0-9a-fA-F]{40}) refs\\/(heads|tags)\\/(.*?)( |00|\u0000)|^(0000)$")
```

It will fail to match that perfectly valid input, just because the read boundary happened to fall inside it.

This can be tested easily by using a helper wrapper `io.Reader` that always reads no more than 1 byte at a time:

```Go
// fragmentedReader reads from R, with each Read call returning at most fragmentLen bytes even
// if len(p) is greater than fragmentLen.
// It purposefully adds a layer of inefficiency around R, and exists for testing purposes only.
type fragmentedReader struct {
	R io.Reader // Underlying reader.
}

func (r fragmentedReader) Read(p []byte) (n int, err error) {
	const fragmentLen = 1
	if len(p) <= fragmentLen {
		return r.R.Read(p)
	}
	return r.R.Read(p[:fragmentLen])
}
```

I have a PR coming that will resolve this issue.

### LINKED ISSUE #15: githttp.RpcReader: No tests.
`githttp.RpcReader` has no tests. This makes it very hard to refactor, optimize, or fix bugs in it, because there's no way of knowing if making changes to it will result in regressions in behavior.

There should be some tests that ensure some sort of basic functionality, so that future changes to the code can be checked to not break the current behavior. This makes it much easier for contributors to submit improvements or fixes as well.

I have a PR coming that will add some tests for the current behavior. The tests will also catch additional issues that I've discovered and fixed in the same PR.

### LINKED ISSUE #16: githttp.RpcReader: Very inefficient and slow operation for "receive-pack" with huge PACK binary sections.
The typical usage of `githttp.RpcReader` is to pass the entire input to `git-receive-pack` through it.

```Go
// Copy input to git binary
io.Copy(stdin, rpcReader)
```

The way it operates internally is that it scans the entire data with a regexp via successive calls to `scanPush`:

```Go
func scanPush(data []byte) []Event {
	matches := receivePackRegex.FindAllStringSubmatch(string(data[:]), -1)

	if matches == nil {
		return []Event{}
	}

	events := []Event{}
	for _, m := range matches {
		e := Event{
			Last:   m[1],
			Commit: m[2],
		}

		// Handle pushes to branches and tags differently
		if m[3] == "heads" {
			e.Type = PUSH
			e.Branch = m[4]
		} else {
			e.Type = TAG
			e.Tag = m[4]
		}

		events = append(events, e)
	}

	return events
}
```

This can become extremely inefficient and slow for certain inputs to receive-pack. Namely, when the receive-pack data includes a huge PACK binary section.

```
00a30000000000000000000000000000000000000000 92eef6dcb9cc198bc3ac6010c108fa482773f116 refs/heads/master<nul> report-status side-band-64k agent=git/2.5.4.(Apple.Git-61)
0000
PACK<nul><nul><nul><nul><nul>??x???K
?<nul>?9Ż??_M"
v?=???????f?22U?8g?â?I'???В???G
H֨???%?????????????????uHؽ?/??)?{P?R?????R,?oK?V1r?????<???#p?4??>?ε?<nul>m???#x???Mn???>w]41?#??QP$?h/J??dj@?????? >~?|R"??3m՟Omg?Uk,֍%??5f?i??+
q???

{{ Potentially 50-1000+ MB of binary git PACK data here. }}

?֟???"v???ƶ]k]e???5OI??O(?????_?????2c??K??MWu?5|???*??=???tC?f????	?8?0c?m{{50+ MB of binary pack data omitted for brevity.}}??5?+j???l*?gb<nul>
??Wn???-??X??Rы?<nul>?ku?x?31<nul>??Ң??Ă??r;e_{W???[Kaq??	DUa1×~?;i?mr??;?????v<nul>L???|x????}C;?H?????V??or?{?<nul>??!???_x?????r?ѝ*]??W7????ˣ7?=?????x?{Ƹ?q??g?<nul>L??8x?[?????HX?ۺ5????u????????^l<nul>????fx?[?????HN???끗&??????O???<nul>?3???x?{b??3??aj??????q??i?????a???AR????Ijb??YZ?y??A?mFK9<nul>???#??=!??n?	???6??
```

That can happen when pushing a large amount of commits/code. For example, consider a huge repository, and pushing all of its data into a new remote. The PACK binary section can be arbitrarily large, for example 50 MB, 100 MB, 1+ GB, etc.

Running that regexp on the entire PACK section is unnecessary, incorrect (there may be false positive matches, although very unlikely), and very slow/CPU intensive.

The good news is that it's entirely avoidable. The receive-pack format begins with a set of pkt-lines that are quite easy to parse. The pkt-line format is described and documented here:

- https://git-scm.com/book/en/v2/Git-Internals-Transfer-Protocols
- https://github.com/git/git/blob/master/Documentation/technical/protocol-common.txt
- https://github.com/git/git/blob/master/Documentation/technical/http-protocol.txt
- https://github.com/git/git/blob/master/Documentation/technical/pack-protocol.txt

A much more efficient solution is to parse only the pkt-lines, and when reaching the end (indicated by a "0000" flush-pkt message), stop scanning the rest, which will be a PACK binary section.

### PR DESCRIPTION
**Pull request by shurcooL**
The major goal of this refactor is to avoid a very glaring problem that the `receivePackRegex` regexp is used on all of receive-pack data, including the pkt-lines but also binary PACK section. This can be a
problem for large git push operations that include PACK section sizes of 50 MB, 100 MB, or any arbitrarily greater size. Running a regexp over all that binary data can be very expensive, and it's completely unnecessary since the matches can only occur within the small pkt-lines section (on the order of a few KB at the most).

The pkt-line format is described and documented here:

- https://git-scm.com/book/en/v2/Git-Internals-Transfer-Protocols
- https://github.com/git/git/blob/master/Documentation/technical/protocol-common.txt
- https://github.com/git/git/blob/master/Documentation/technical/http-protocol.txt
- https://github.com/git/git/blob/master/Documentation/technical/pack-protocol.txt

In addition to resolving the problem described above, other correctness bugs were fixed, and some style simplifications were made.

Finally, tests are added both to ensure the new behavior is correct and to avoid regressions. The tests also successfully detect some discovered bugs in the previous code.

Fixes #16.
Fixes #15.
Fixes #14.
Fixes #13.

## Results

In my local testing, this reduces the overhead of using `githttp.RpcReader` significantly, almost to zero relative to the rest of the work that git performs. Previously, large git pushes were significantly slowed down by `githttp.RpcReader`.

Pushing an entire 50~ MB git repository locally (over localhost, no network) with the original `githttp` code takes 7.680 seconds:

```
$ time git push local master
Counting objects: 47641, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (23156/23156), done.
Writing objects: 100% (47641/47641), 56.55 MiB | 8.84 MiB/s, done.
Total 47641 (delta 21640), reused 46854 (delta 21124)
To ssh://git@localhost:3022/large-repo-push-test
 * [new branch]      master -> master

real    0m7.680s
user    0m0.636s
sys     0m0.302s
```

After applying this optimization, the performance is much faster. It becomes just under 2 seconds:

```
$ time git push local master
Counting objects: 47641, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (23156/23156), done.
Writing objects: 100% (47641/47641), 56.55 MiB | 46.22 MiB/s, done.
Total 47641 (delta 21640), reused 46854 (delta 21124)
To ssh://git@localhost:3022/large-repo-push-test
 * [new branch]      master -> master

real    0m1.955s
user    0m0.582s
sys     0m0.160s
```

The write speed went from 8.84 MiB/s to 46.22 MiB/s, which is almost the same speed as when `githttp.RpcReader` is skipped completely.

(I was careful to delete the target repository before each push test, so the improved performance is representative of real improvements, and not a result of the git commits already being present.)

### CODE REVIEW

**Comment by AaronO** [comment]
@shurcooL Reviewing this now :)

First of all thanks for the PR, it's something that I had on my TODO list and wanted to optimize at some point (my first concern was to have it working).

Either way the unit tests and refactoring along with the performance increase is awesome ! :+1:

**Comment by AaronO** [comment]
@shurcooL This looks good !

One tiny nitpick: `parser.go` can be a bit ambiguous to what it really does, what do you think of renaming that to `pkt_parser.go` or `pktparser.go` ?

**Comment by shurcooL** [comment]
> One tiny nitpick: `parser.go` can be a bit ambiguous to what it really does, what do you think of renaming that to `pkt_parser.go` or `pktparser.go`?

I named it `parser.go` since there was no other such file now, and I figured if in the future there will be, it can then be renamed to a more specific name like `pktlineparser.go`. But I can do that now if you wish. The type is already called `pktLineParser`.

**Comment by AaronO** [comment]
Yep, it wasn't crucial, but I think having it in the name helps to grasp what it does in a single glance.

Merging this now ! Thanks again for the awesome PR :+1:

**Comment by shurcooL** [comment]
Thanks! I'm glad you liked it too.

Just as a heads up, I will have another PR tomorrow that will add some more (currently failing) tests and resolve them. I will report the issue details too. You can take a sneak peak at https://github.com/sourcegraph/go-git-http/commit/bc537c7d407b2c4e43a586443243a40e2e2a5632.

**Pull request merged**
